name: Deploy
on:
  push:
    branches: feature/pwa
  pull_request:
    branches: feature/pwa

jobs:
  deploy-frontend:
    name: Deploy Frontend
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Install Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install dependencies
        run: "deno install"

      - name: Build
        run: "deno task build"

      - name: Deploy to Deno Deploy
        uses: denoland/deployctl@v2
        with:
          project: "cdwishlist"
          entrypoint: "deploy.ts"

  deploy-signaling:
    name: Deploy Signaling Server
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Install Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Deploy to Deno Deploy
        uses: denoland/deployctl@v2
        with:
          project: "cdwishlist-signaling"
          entrypoint: "signaling-server.ts"
